var dialog = [];

function loadScript(){
    console.log("Scripts loaded ...")
    dialog[0] = "yara(happy)-It feels like I'm being sent on a fool's errand."
    dialog[1] = "yara(happy)-Talking trees and winged rabbits? ..."
    dialog[2] = "yara(happy)-But what else can I do?"
    dialog[3] = "yara(happy)-... It's worth the try!"
    dialog[4] = "yara(happy)-Okay! What tools do I need for this ‘quest’ ?-END"
    dialog[5] = "yara(happy)-Now's not the time to sit, Yara.\n You need to get ready to head out...-END"
    dialog[6] = "yara(happy)-I remember when these were just sprouts.\nI wish I did more to take care of them (saddness)...-END"
    dialog[7] = "yara(happy)-The village has changed so much...-END"    
    dialog[8] = "yara(happy)-Alright! Lets go Yara.. "
    dialog[9] = "yara(happy)-You can do this!-NEXTSCENE"

    dialog[10] = "yara(happy)-It's been a few short years ..."
    dialog[11] = "yara(happy)-And now these streets are so different than I remember"
    dialog[12] = "yara(happy)-Cold dark towers grasping for the sky ..."
    dialog[13] = "yara(happy)-Wires choking everything ..."
    dialog[14] = "yara(happy)-Strange 'birds' everywhere ..."
    dialog[15] = "yara(happy)-Wait ... is that a feather?-END"
    dialog[16] = "yara(happy)-Pretty"
    dialog[17] = "yara(happy)-I see more in the distance"
    dialog[18] = "yara(happy)-Whatever left these seems to have been heading to the swamp?-NEXTSCENE"

    dialog[19] = "yara(happy)-The great old Boabab Tree..."
    dialog[20] = "yara(happy)-Is that the one they spoke of?"
    dialog[21] = "yara(happy)-I don't remember it ever talking though ..."
    dialog[22] = "yara(happy)-Maybe I need to reach it first?-NEXTSCENE"

    dialog[23] = "yara(happy)-This swamp is so dense ...\nAnd these look so similar to the choking wires .."
    dialog[24] = "yara(happy)-What's with these creepy birds everywhere?"
    dialog[25] = "yara(happy)-Maybe if I use my knife I can cut my way through?-END"
    dialog[26] = "yara(happy)-No matter how much I cut the vines keep growing back"
    dialog[27] = "???(happy)-LEAVE ME ALONE!!!!!!!"
    dialog[28] = "yara(happy)-It seems like someone … or something… needs help -NEXTSCENE"


    dialog[29] = "rabbit(happy)-LEAVE ME ALONE YOU STRANGE LOOKING BIRDS!"
    dialog[30] = "rabbit(happy)-STOP WATCHING ME ALL THE TIME!!!"
    dialog[31] = "rabbit(happy)-YOUR RED EYES ARE CRIPPLING!!!"
    dialog[32] = "yara(happy)-Those strange birds again!\n Wait ... what is that rabbit doing?-RABBITFLY"
    dialog[33] = "rabbit(happy)-I CAN'T GET AWAY!"
    dialog[34] = "yara(happy)-Wait…. Did that rabbit just try to fly?\nMaybe I can use my knife to scare the birds away?-END"
    dialog[35] = "yara(happy)-Away with you Vile Bird!-END"
    dialog[36] = "yara(happy)-You tried to fly ... and you're a rabbit ...\nI think I was sent to find you!\nIm Yara, and I am looking for a Talking Boabab"
    dialog[37] = "rabbit(happy)-How convenient for you to find me this way then.\nI guess I owe you one ..."
    dialog[38] = "rabbit(happy)-Wait a Talking Boabab?\nIn that case we don't have much time , Lets GO!-NEXTSCENE"

    dialog[39] = "yara(happy)-Okay we're back on the path to the Boabab...-END"
    dialog[40] = "yara(happy)-SIGH\nNo matter how much I cut the vines keep growing back"
    dialog[41] = "rabbit(happy)-That's because the swamp is ALIVE!"
    dialog[42] = "yara(happy)-I know ... these are living plants after all..."
    dialog[43] = "rabbit(happy)-No.\nI mean alive in the sense that it has a spirit"
    dialog[44] = "rabbit(happy)-One that demands respect\nOne that responds to your aggressive energy"
    dialog[45] = "yara(happy)-Okay. You've lost me ...-SETFLAG-rabbitInstruct-1"
    dialog[46] = "rabbit(happy)-Use your hand, Yara.\nPush the vines aside with your HANDS.-END"
    var saveKey =parseInt(localStorage.getItem("saveKey"))
    var rabbitInstruct = parseInt(localStorage.getItem(saveKey+'rabbitInstruct'))
    if(rabbitInstruct == 1){
        dialog[47] = "yara(happy)-Well I'll be ...\nYou were right, Rabbit!"
        dialog[48] = "rabbit(happy)-Of course!\nI know what I'm talking about-NEXTSCENE"
    }
    else{
        dialog[47] = "yara(happy)-SIGH\nTime to use my trusty Knife ... again-END"
    }

   dialog[49] = "rabbit(happy)-Before we meet the Boabab we need to find an appropriate gift."
   dialog[50] = "yara(happy)-A gift?"
   dialog[51] = "rabbit(happy)-Yes. The Talking Boabab has been ... differnt lately."
   dialog[52] = "rabbit(happy)-Maybe a gift can remind itself of it's duties"
   dialog[53] = "rabbit(happy)-I think that's the plant we need\nBut the spinetail is in front of the Lumina Plant"
   dialog[54] = "rabbit(happy)- The lumina!\nYes, It's the perfect gift for the baobab!"
   dialog[55] = "yara(happy)-I have the right tool for this! All weird birds fear my trusty knife!"
   dialog[56] = "rabbit(happy)-Uhhhh...\nmaybe this bird is different?\nCan’t you see that? "
   dialog[57] = "yara(happy)-But don't we need it out of the way?"
   dialog[58] = "rabbit(happy)-You might have to learn one or two things\nabout detail and ... patience ..."
   dialog[59] = "spinetail(neutral)-So Hungry ... "
   dialog[60] = "yara(happy)-Well we need Mr SpineTail here to move ... "
   dialog[61] = "yara(happy)-Maybe these bugs might be useful for something?"
   dialog[62] = "yara(happy)-Okay. Let's feed Mr. Spinetail and harvest a Lumina Plant"
   dialog[63] = "rabbit(happy)-Sounds like a plan-END"
   dialog[64] = "yara(happy)-Got a creepy crawly-END"
   dialog[65] = "spinetail(neutral)-So weak ... So hungry-END"
   dialog[66] = "spinetail(happy)-Yummy! I feel my strength returning-END"
   dialog[67] = "spinetail(happy)-Thanks for the Grub Bub!\nSee ya!-END"
   dialog[68] = "spinetail(neutral)-Put that away!\nDon't threaten me!-END"
   dialog[69] = "rabbit(happy)-Remember Yara.\m Use your hands to move the plants"
   dialog[70] = "yara(happy)-Right-END"
   dialog[71] = "rabbit(happy)-Now you can gently harvest the Lumina plant, Yara"
   dialog[72] = "yara(happy)-Okay. Here we go...-END"
   dialog[73] = "yara(happy)-Got it!"
   dialog[74] = "rabbit(happy)-Excellent!\nNow let's continue making our way to the Talking Boabab-NEXTSCENE"
    
   dialog[75] = "yara(happy)-Wow. The Boabad truly is massive ..."
   dialog[76] = "yara(happy)-But look at all the wires ...\nI didn't know they reached this far into the swamp?"
   dialog[77] = "boabab(happy!)-.... Who approaches? ...." 
   dialog[78] = "yara(happy)-Oh it does Talk!"
   dialog[79] = "boabab(happy!)-... Leave ... Me ...."
   dialog[80] = "yara(happy)-But we need your help.\nI was told to find you... to find a Queen?"
   dialog[81] = "rabbit(happy)-I was worried about this ...\nThe Talking Boabab has forgotten itself"
   dialog[82] = "rabbit(happy)-It used to be kind ..."
   dialog[83] = "rabbit(happy)-Yara! You must present your gift\nRemind the Talking Boabab what it stands for!-END"
   dialog[84] = "boabab(happy!)-.... You dare to threaten ME? ...."
   dialog[85] = "rabbit(happy)-No Yara!\nThe  gift! The Lumina plant-END"
   dialog[86] = "boabab(happy!)-.... I REMEMBER...! ....-FLASH"
   dialog[87] = "boabab(happy!)-.... Thank...you ...."
   dialog[88] = "boabab(happy!)-.... I will take ... you where you ... need to go ....-SETFLAG-treeInstruct-1"
   dialog[89] = "boabab(happy!)-.... Touch my trunk and I'll transport you to the Queen ....-END"
   dialog[90] = "rabbit(happy)-Ready Yara?"
   dialog[91] = "yara(happy)-Yes. Let's go ..."
   dialog[92] = "yara(happy)-(Yara places her hands on the trunk of the Talking Boabab)-NEXTSCENE"

   dialog[93] = "yara(happy)-Woah!\nThat was incredible ..."
   dialog[94] = "yara(happy)-Now where are we ..."
   dialog[95] = "villager(happy)-Welcome to our village, Yara.\nThe Queen is expecting you."
   dialog[96] = "rabbit(happy)-Great!\nCan you lead us to her?"
   dialog[97] = "villager(happy)-Unfortunately...\nbefore I can direct you I need to finish my tasks"
   dialog[98] = "villager(happy)-I need to complete the planting this season's crops..."
   dialog[99] = "villager(happy)-But these strange birds they keep taking the seeds"
   dialog[100] = "villager(happy)-They don't even eat them.\nThey just take and take and given nothing back..."
   dialog[101] = "yara(happy)-Well I'm very good at scarying away creepy birds ...-END"
   dialog[102] = "yara(happy)-Leave those seeds alone!-END"
   dialog[103] = "yara(happy)-Away with you!-END"
   dialog[104] = "yara(happy)-Shoo!-END"
   dialog[105] = "yara(happy)-I should use my trusty knife right?"
   dialog[106] = "rabbit(happy)-I don't see why not?-END"
   dialog[107] = "villager(happy)-Thank you!\nNow do you think you could help with planting the seeds?"
   dialog[108] = "yara(happy)-Sure!"
   dialog[109] = "villager(happy)-Excellent!\nHere take these-GIVESEED"
   dialog[110] = "villager(happy)-Well done. Now all that left is to water them."
   dialog[111] = "villager(happy)-Take this bucket and use the well to gather the water-GIVEBUCKET"
   dialog[112] = "yara(happy)-There! Bucket filled!\nWow this bucket is heavy!-END"
   dialog[113] = "villager(happy)-Thank you!\nTake these Neem leaves as a token of appreciation\nI will guide you to the Queen now-GIVENEEM"
   
   dialog[114] = "yara(happy)-Greetings your Majesty.\nI was sent on a quest to find you.\nI was told that you'd help us."
   dialog[115] = "Queen(happy)-I have been expecting you, Yara."
   dialog[116] = "Queen(happy)-What you seek can be found in the forest across the river"
   dialog[117] = "Queen(happy)-... But I fear that you are not ready"
   dialog[118] = "yara(happy)-Of course I am!"
   dialog[119] = "yara(happy)-I've braved the swamp ..."
   dialog[120] = "yara(happy)-Faced the birds ..."
   dialog[121] = "yara(happy)-Been blessed by the Talking Boabab ..."
   dialog[122] = "yara(happy)-I think I'm ready!"
   dialog[123] = "Queen(happy)-Well be on your way then ...-NEXTSCENE"

   dialog[124] = "rabbit(happy)-Don't you think you were a bit rude back there, Yara?"
   dialog[125] = "yara(happy)-Don't be silly, Rabbit.\nWe're more than ready for what comes next"
   dialog[126] = "yara(happy)-See?\nWe just need to cross the river\nand then our quest will be complete"
   dialog[127] = "yuleni(happy)-Yara .... !-SHOW-s11o1"
   dialog[128] = "yara(happy)-Yuleni?"
   dialog[129] = "yuleni(happy)-Yara .... why did you abandon us???"
   dialog[130] = "yara(happy)-How ... How are you here?"
   dialog[131] = "yuleni(happy)-Yara ...."
   dialog[132] = "rabbit(happy)-Yara!\n Snap out of it!\nI don't think that person is real!"
   dialog[133] = "yara(happy)-No ... I'm sorry, Yuleni.\n I'm ... Sorry"
   dialog[134] = "yara(happy)-(Yara cries softly)-CHOICE-GO BACK-135-STAY-130"
   dialog[135] = "rabbit(happy)-Maybe the Queen can help us...-NEXTSCENE"

   dialog[136] = "Queen(happy)-Welcome back Yara"
   dialog[137] = "yara(happy)-(yara continues to sob quietly)"
   dialog[138] = "rabbit(happy)-Your Majesty ... I don't understand what happened"
   dialog[139] = "rabbit(happy)-A person appeared before us ...\nand suddenly Yara became inconsolable"
   dialog[140] = "Queen(happy)-I see you've met the jabberjay"
   dialog[141] = "yara(happy)-Jabberjay?"
   dialog[142] = "Queen(happy)-Yes. It's a vile bird that brings distress.\nThey mimick our loved ones and give voice to our darkest fears"
   dialog[143] = "yara(happy)-So that wasn't Yuleni?\nYuleni doesn't hate me?"
   dialog[144] = "Queen(happy)-No Yara. But that doesn't remove the sting from it's words"
   dialog[145] = "Queen(happy)-To progress you need to strengthen your will ...\nand temper your mind"
   dialog[146] = "Queen(happy)-Come I will show you a ceremony that will lend you strength-NEXTSCENE"

   dialog[147] = "Queen(happy)-We will make an inkbalm"
   dialog[148] = "Queen(happy)-We will use this ink to give you markings"
   dialog[149] = "Queen(happy)-These marking will help you remember yourself ...\nand give you confidence to peservere"
   dialog[150] = "Queen(happy)-Here take these Shea leaves ...\nand combine it with the gifts you've gathered...-GIVESHEA"

   dialog[151] = "Queen(happy)-Well done."
   dialog[152] = "Queen(happy)-Now we grind the plants into a paste"
   dialog[153] = "Queen(happy)-Like so ..."
   dialog[154] = "Queen(happy)-(The Queen grinds the ingredients in the mortar)-GRIND"
   dialog[155] = "Queen(happy)-And it is done..."
   dialog[156] = "Queen(happy)-Use this paste to draw markings on your skin."
   dialog[157] = "yara(marked)-... I feel different"
   dialog[158] = "Queen(happy)-Perfect."
   dialog[159] = "Queen(happy)-Now you are ready-NEXTSCENE"

   dialog[160] = "yuleni(happy)-Yara ....."
   dialog[161] = "yara(marked)-I won't fall for your tricks again!-HIDE-s14o1"
   dialog[162] = "rabbit(happy)-You tell him, Yara!-SHOW-s14o2"
   dialog[163] = "yara(marked)-I know what to do now...\nthat you've revealed yourself vile bird-END"
   dialog[164] = "yara(marked)-Begone!"
   dialog[165] = "rabbit(happy)-Look Yara\nA path to cross the river-SHOW-s14o3"
   dialog[166] = "yara(marked)-And one step closer to finishing this quest-FINAL"
   
    


}